---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHVra3E2b3hyCg==
  CLOUDINARY_KEY: NDU1NTQ0NTk4NDg1NTI5Cg==
  CLOUDINARY_SECRET: TG0ydGNlRHU4ZzcydDRRdGttaHF0bldQdjhBCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2ljMjFoY25Sd2F5SXNJbUVpT2lKamJIWnJaWEJpWTJReGVUTnVNbWx3WldnMGFtaHBkSEZ4SW4wLklzQ0VucUxNMzkwMERQbmp6RExyencK
  DB_URL: bW9uZ29kYitzcnY6Ly9wcmF2ZWVueWFkYXZwazQ1OnZwQ05VZUU3ZmVWSElTOFFAbm9kZWpzLmpiZXViZXYubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPU5vZGVqcwo=
  SECRET: c21hcnRwawo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: smartpk1234/camp:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          #livenessProbe:
            #httpGet:
              #path: /
              #port: 3000
            #initialDelaySeconds: 30   # Adjust the initial delay here
          #readinessProbe:
            #httpGet:
              #path: /
              #port: 3000
            #initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
